name: generate ascii art refactor
on: push
jobs:
  ascii-job-refactor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: install cowsay program
        run: | 
         sudo apt-get install cowsay -y
         cowsay -f dragon "I am a Dragon raaaarwww" >> sample.txt
         grep -i "dragon" sample.txt
         ls -a
         cat sample.txt
         ls -ltra

      # - name: execute cowsay command
      #   run: cowsay -f dragon "I am a Dragon raaaarwww" >> sample.txt

      # - name: check if file exist
      #   run: grep -i "dragon" sample.txt

      # - name: list hidden files
      #   run: ls -a

      # - name: Read file 
      #   run: cat sample.txt

      # - name: list repo files
      #   run: ls -ltra