name: my-first-workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: welcome message
              run: |
                echo "This is a welcomme message"
                ls
                grep -rl "test"
                grep -i "first" README.md
                cat README.md

            # - name: list files
            #   run: ls

            # - name: check file for words
            #   run: grep -rl "test"

            # - name: Read files
            #   run: cat README.md